apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - Validate=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/JvictorMarques/gitops
    path: k8s
    directory:
      include: deploy.yaml
    targetRevision: HEAD
  destination:
    namespace: webcolor
    server: https://kubernetes.default.svc