apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /status/currentReplicas
    - /status/desiredReplicas
  source:
    repoURL: https://github.com/JvictorMarques/gitops
    path: k8s
    directory:
      include: chaos.yaml
    targetRevision: HEAD
  destination:
    namespace: chaos
    server: https://kubernetes.default.svc