apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: waves
  namespace: argocd
spec:
  project: web
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/JvictorMarques/gitops
    path: k8s
    include: waves.yaml
    targetRevision: HEAD
  destination:
    namespace: waves
    server: https://kubernetes.default.svc