apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/JvictorMarques/gitops
    path: k8s/app
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc