---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pre-sync
        image: curlimages/curl:latest

        command: 
        - /bin/sh
        - -c
        - |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"message": "Hello from ArgoCD pre-sync hook!"}' \
          https://webhook.site/6fe0d5be-2927-42c5-a6df-6e8e7b5b3960
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-hook
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: sync
        image: curlimages/curl:latest

        command: 
        - /bin/sh
        - -c
        - |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"message": "Hello from ArgoCD sync hook!"}' \
          https://webhook.site/6fe0d5be-2927-42c5-a6df-6e8e7b5b3960
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: post-sync
        image: curlimages/curl:latest

        command: 
        - /bin/sh
        - -c
        - |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"message": "Hello from ArgoCD post-sync hook!"}' \
          https://webhook.site/6fe0d5be-2927-42c5-a6df-6e8e7b5b3960
      restartPolicy: Never
