apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/JvictorMarques/gitops
    path: k8s/manifests
    directory:
      include: blue.yaml
    targetRevision: HEAD
  destination:
    namespace: blue
    server: https://kubernetes.default.svc